users = [
    {"username": "PlayerOne", "status": "online", "game": "Minecraft"},
    {"username": "GamerGirl123", "status": "offline", "game": None},
    {"username": "SpeedRacer", "status": "online", "game": "Forza Horizon 5"},
    {"username": "CoolDude", "status": "offline", "game": None},
    {"username": "AceShooter", "status": "online", "game": "Call of Duty"},
    {"username": "QuickFox", "status": "offline", "game": None},
    {"username": "ProGamer99", "status": "online", "game": "Apex Legends"},
    {"username": "ShadowHunter", "status": "offline", "game": None},
    {"username": "NinjaTurtle", "status": "offline", "game": None},
    {"username": "EliteSniper", "status": "online", "game": "Counter-Strike"},
    {"username": "DragonSlayer", "status": "offline", "game": None},
    {"username": "WarriorX", "status": "offline", "game": None},
    {"username": "GalaxyStar", "status": "offline", "game": None},
    {"username": "BlazeMaster", "status": "online", "game": "League of Legends"},
    {"username": "SilentStorm", "status": "offline", "game": None},
    {"username": "RogueAgent", "status": "online", "game": "Valorant"},
    {"username": "TechGuru", "status": "offline", "game": None},
    {"username": "SkyWalker", "status": "offline", "game": None},
    {"username": "NightWolf", "status": "offline", "game": None},
    {"username": "GameWizard", "status": "online", "game": "World of Warcraft"},
]
